name: Build

run-name: Build [${{github.run_number}}] [${{github.event.head_commit.message}}]

on:
  push:
    branches-ignore: "master"

  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted
    container:
      image: sjaekim/kuase_dev:v0.7

    env:
        BUILD_TYPE: Release

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      
    - name: Install Boost
      run: |
        sudo apt update
        sudo apt install -y libboost-all-dev
        
    - name: Configure Submodules
      run: |
        git config --global --add safe.directory '*'
        git submodule update --init --recursive
    
    - name: Configure CMake Environment
      run: cmake -B $GITHUB_WORKSPACE/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build the project
      run: cmake --build $GITHUB_WORKSPACE/build --config ${{env.BUILD_TYPE}}
            
    - name: Upload build directory
      uses: actions/upload-artifact@v4
      with:
        name: build-dir
        path: build/
        if-no-files-found: error

  
